environment:
  matrix:
    - image: Visual Studio 2017
      generator: "Visual Studio 15 2017"
    - image: Visual Studio 2019
      generator: "Visual Studio 16 2019"

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - if exist build RMDIR /S /Q build
  - mkdir build
  - cmake -Ssrc -Bbuild -G "%generator%" -A %platform% -DCMAKE_BUILD_TYPE=%configuration% -Wdev -Wdeprecated

build:
  project: build/bomberman.sln
  parallel: true
  verbosity: minimal
